### DISCUSSION TITLE
[BE] Entity를 변경하고 다시 시작해도, db에 반영이 안되는 이유

### DISCUSSION THREAD

**Discussion by 2020147542** [UMC-CodePlay/CodePlay-BE#125] [General]
## 문제 상황
Entity 변경하고 애플리케이션 재시작했는데 DB에 반영이 안되는 문제가 발생했음. Docker로 MySQL 실행하면서 volumes 쓰고 있음

### docker/local/docker-compose.yml 내부
```yaml 
services:
  mysql:
    volumes:
      - data:/var/lib/mysql    # 여기가 문제임
```

### docker/deploy/docker-compose.yml 내부
```yaml 
services:
  database:
    volumes:
      - /home/ubuntu/deploy-db:/var/lib/mysql # 여기가 문제임
```

## 원인
Docker volume이 데이터를 보존하는 저장소임. 스프링 어플리케이션을 재시작해도 이전 데이터가 그대로 남아있어서 변경된 Entity가 반영이 안 되는 것임
